In [1]:
pip install pandas-profiling

Requirement already satisfied: pandas-profiling in c:\users\ssingirikonda\anaconda3\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.16.0 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (1.19.2)
Requirement already satisfied: scipy>=1.4.1 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (1.5.2)
Requirement already satisfied: joblib in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (0.17.0)
Requirement already satisfied: PyYAML>=5.0.0 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (5.3.1)
Requirement already satisfied: htmlmin>=0.1.12 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (0.1.12)
Requirement already satisfied: phik>=0.11.1 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (0.12.0)
Requirement already satisfied: tqdm>=4.48.2 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (4.50.2)
Requirement already satisfied: pydantic>=1.8.1 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (1.8.2)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (2.11.2)
Requirement already satisfied: seaborn>=0.10.1 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (0.11.0)
Requirement already satisfied: tangled-up-in-unicode==0.1.0 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (0.1.0)
Requirement already satisfied: missingno>=0.4.2 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (0.5.0)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (1.1.3)
Requirement already satisfied: matplotlib>=3.2.0 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (3.3.2)
Requirement already satisfied: visions[type_image_path]==0.7.1 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (0.7.1)
Requirement already satisfied: requests>=2.24.0 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas-profiling) (2.24.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pydantic>=1.8.1->pandas-profiling) (3.7.4.3)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from jinja2>=2.11.1->pandas-profiling) (1.1.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2.8.1)
Requirement already satisfied: certifi>=2020.06.20 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (2020.6.20)
Requirement already satisfied: cycler>=0.10 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (8.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.3.0)
Requirement already satisfied: bottleneck in c:\users\ssingirikonda\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.1->pandas-profiling) (1.3.2)
Requirement already satisfied: attrs>=19.3.0 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.1->pandas-profiling) (20.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.1->pandas-profiling) (2.5)
Requirement already satisfied: multimethod==1.4 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.1->pandas-profiling) (1.4)
Requirement already satisfied: imagehash; extra == "type_image_path" in c:\users\ssingirikonda\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.1->pandas-profiling) (4.2.1)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (1.25.11)
Requirement already satisfied: six>=1.5 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (1.15.0)
Requirement already satisfied: decorator>=4.3.0 in c:\users\ssingirikonda\anaconda3\lib\site-packages (from networkx>=2.4->visions[type_image_path]==0.7.1->pandas-profiling) (4.4.2)
Requirement already satisfied: PyWavelets in c:\users\ssingirikonda\anaconda3\lib\site-packages (from imagehash; extra == "type_image_path"->visions[type_image_path]==0.7.1->pandas-profiling) (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [12]:
import pandas as pd
xls = pd.ExcelFile('HospitalDatabase.xlsx')
discharge_df = pd.read_excel(xls, 'Discharges')
patients_df = pd.read_excel(xls, 'Patients')
visits_df = pd.read_excel(xls, 'EDVisits')

In [5]:
from pandas_profiling import ProfileReport
prof = ProfileReport(discharge_df)
prof.to_file(output_file='output.html')

HBox(children=(HTML(value='Summarize dataset'), FloatProgress(value=0.0, max=22.0), HTML(value='')))

HBox(children=(HTML(value='Generate report structure'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(HTML(value='Render HTML'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(HTML(value='Export report to file'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

#### Another very basic and widely used functions. Because it is necessary to know the data types of the variables before we dive into the analysis, visualization, or predictive modeling.

In [5]:
# dtypes is used to find the datatypes of the variables
discharge_df.dtypes

AdmissionID                      int64
PatientID                        int64
AdmissionDate           datetime64[ns]
DischargeDate           datetime64[ns]
DischargeDisposition            object
Service                         object
PrimaryDiagnosis                object
ExpectedLOS                    float64
ExpectedMortality              float64
dtype: object

#### You can select the variables or columns of a certain data type using this function. For example, I want to select the columns with data types ‘int64’ only from discharges dataframe we can use the below statement

In [6]:
discharge_df.select_dtypes(include='int64')

     AdmissionID  PatientID
0              1          9
1            257         93
2            152        101
3            361        102
4            258        103
..           ...        ...
715          715        716
716          698        723
717          704        724
718          716        733
719          710        742

[720 rows x 2 columns]

#### Create multiple graphs in one canvas using ggplot2

In [11]:
pip install plotnine

Collecting plotnine
  Downloading plotnine-0.8.0-py3-none-any.whl (4.7 MB)
     ---------------------------------------- 4.7/4.7 MB 4.7 MB/s eta 0:00:00
Collecting patsy>=0.5.1
  Downloading patsy-0.5.2-py2.py3-none-any.whl (233 kB)
     -------------------------------------- 233.7/233.7 kB 4.9 MB/s eta 0:00:00
Collecting descartes>=1.1.0
  Downloading descartes-1.1.0-py3-none-any.whl (5.8 kB)
Collecting statsmodels>=0.12.1
  Downloading statsmodels-0.13.2-cp310-cp310-win_amd64.whl (9.1 MB)
     ---------------------------------------- 9.1/9.1 MB 5.2 MB/s eta 0:00:00
Requirement already satisfied: matplotlib>=3.1.1 in c:\python\python310\lib\site-packages (from plotnine) (3.5.2)
Requirement already satisfied: scipy>=1.5.0 in c:\python\python310\lib\site-packages (from plotnine) (1.8.1)
Collecting mizani>=0.7.3
  Downloading mizani-0.7.4-py3-none-any.whl (63 kB)
     ---------------------------------------- 63.7/63.7 kB 3.3 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.19.0 in c:\python\python310\lib\site-packages (from plotnine) (1.22.3)
Requirement already satisfied: pandas>=1.1.0 in c:\python\python310\lib\site-packages (from plotnine) (1.4.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\python\python310\lib\site-packages (from matplotlib>=3.1.1->plotnine) (3.0.9)
Requirement already satisfied: packaging>=20.0 in c:\python\python310\lib\site-packages (from matplotlib>=3.1.1->plotnine) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\python\python310\lib\site-packages (from matplotlib>=3.1.1->plotnine) (1.4.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\python\python310\lib\site-packages (from matplotlib>=3.1.1->plotnine) (4.33.3)
Requirement already satisfied: pillow>=6.2.0 in c:\python\python310\lib\site-packages (from matplotlib>=3.1.1->plotnine) (9.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\python\python310\lib\site-packages (from matplotlib>=3.1.1->plotnine) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\python\python310\lib\site-packages (from matplotlib>=3.1.1->plotnine) (0.11.0)
Collecting palettable
  Downloading palettable-3.3.0-py2.py3-none-any.whl (111 kB)
     -------------------------------------- 111.8/111.8 kB 6.4 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2020.1 in c:\python\python310\lib\site-packages (from pandas>=1.1.0->plotnine) (2022.1)
Requirement already satisfied: six in c:\python\python310\lib\site-packages (from patsy>=0.5.1->plotnine) (1.16.0)
Installing collected packages: palettable, patsy, statsmodels, mizani, descartes, plotnine
Successfully installed descartes-1.1.0 mizani-0.7.4 palettable-3.3.0 patsy-0.5.2 plotnine-0.8.0 statsmodels-0.13.2
Note: you may need to restart the kernel to use updated packages.

In [13]:
count_df = visits_df[['PatientID','ReasonForVisit', 'EDDisposition']].groupby(['ReasonForVisit','EDDisposition']).count()
print(count_df)

# from plotnine import ggplot, aes, labs, geom_point

# (
#     ggplot(visits_df)
#     + aes(x="cyl", y="hwy", color="class")
#     + labs(
#         x="Engine Cylinders",
#         y="Miles per Gallon",
#         color="Vehicle Class",
#         title="Miles per Gallon for Engine Cylinders and Vehicle Classes",
#     )
#     + geom_point()
# )


# # count_df.plot(kind='bar')count_df = visits_df[['PatientID','ReasonForVisit']].groupby(['ReasonForVisit']).count()
# # print(count_df)
# count_df.plot(kind='bar')

                                   PatientID
ReasonForVisit      EDDisposition
Accident            Admitted              39
Bleeding            Admitted              16
                    Discharged            15
Car Accident        Admitted              17
Chest Pain          Admitted              94
                    Discharged            15
Cough               Discharged             1
Fever               Admitted              46
                    Discharged           188
Gun Shot            Admitted              16
Intoxication        Discharged            30
Laceration          Discharged            30
Migraine            Admitted              47
                    Discharged           109
Pneumonia           Admitted             136
                    Discharged            65
Shortness of Breath Admitted              72
                    Discharged            77
Stomach Ache        Admitted              32
                    Discharged           154

#### Spliting the patients data in to 4 quartiles using pd.qcut function
#### qcut will calculate the size of each bin in order to make sure the distribution of data in the bins is equal. In other words, all bins will have (roughly) the same number of observations but the bin range will vary. On the other hand, cut is used to specifically define the bin edges.

In [10]:
from datetime import datetime, date
# Step 1: convert datetime column to just date
patients_df['DateOfBirth'] = pd.to_datetime(patients_df['DateOfBirth']).dt.date

# Step 2: Calculate age(This function converts given date to age)
def age(bdate):
    today = date.today()
    return today.year - bdate.year - ((today.month, 
                                      today.day) < (bdate.month, 
                                                    bdate.day))
  
patients_df['Age'] = patients_df['DateOfBirth'].apply(age)
# display the dataframe with new age column
display(patients_df)
# Step 4: Split the records in to quartiles
labels = ['Below 40','Below 50','Below 60','Below 70']
patients_df['Yr_qcut'] = pd.qcut(patients_df.Age, q=4,
                        labels=labels)
display(patients_df)

,PatientID,FirstName,LastName,DateOfBirth,Gender,Race,Language,Age
0,1,Lanni,Sue,1960-01-01,Male,White,English,62
1,2,Far,Myers,1985-11-15,Male,White,English,36
2,3,Devlin,Michael,1976-04-15,Male,White,English,46
3,4,Carmine,Texas,1968-10-15,Male,White,English,53
4,5,Tann,Bama,1962-05-01,Male,White,English,60
...,...,...,...,...,...,...,...,...
940,941,Wat,Fideler,1986-05-26,Male,Black/African-American,English,35
941,942,Wandie,Baythrop,1970-06-10,Male,Black/African-American,English,51
942,943,Diahann,Smeeton,1983-01-08,Male,Black/African-American,English,39
943,944,Panchito,Sharple,1963-06-05,Male,Black/African-American,English,58
944,945,Walsh,Calvie,1972-08-06,Male,Black/African-American,English,49

,PatientID,FirstName,LastName,DateOfBirth,Gender,Race,Language,Age,Yr_qcut
0,1,Lanni,Sue,1960-01-01,Male,White,English,62,Below 70
1,2,Far,Myers,1985-11-15,Male,White,English,36,Below 40
2,3,Devlin,Michael,1976-04-15,Male,White,English,46,Below 50
3,4,Carmine,Texas,1968-10-15,Male,White,English,53,Below 60
4,5,Tann,Bama,1962-05-01,Male,White,English,60,Below 70
...,...,...,...,...,...,...,...,...,...
940,941,Wat,Fideler,1986-05-26,Male,Black/African-American,English,35,Below 40
941,942,Wandie,Baythrop,1970-06-10,Male,Black/African-American,English,51,Below 60
942,943,Diahann,Smeeton,1983-01-08,Male,Black/African-American,English,39,Below 40
943,944,Panchito,Sharple,1963-06-05,Male,Black/African-American,English,58,Below 70
944,945,Walsh,Calvie,1972-08-06,Male,Black/African-American,English,49,Below 60